# Generated by Django 3.0.7 on 2021-04-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210416_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='message',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
