# Generated by Django 3.0.7 on 2021-10-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_clientlogoitems_portfolioitems_testimonialitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlogoitems',
            name='keyword',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolioitems',
            name='keyword',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='testimonialitems',
            name='keyword',
            field=models.CharField(default='', max_length=20),
        ),
    ]
