# Generated by Django 3.0.7 on 2021-10-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20211001_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitems',
            name='sort_by',
            field=models.CharField(default='', max_length=20),
        ),
    ]
