# Generated by Django 3.0.7 on 2021-10-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20211001_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlogoitems',
            name='sort_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='testimonialitems',
            name='sort_by',
            field=models.CharField(default='', max_length=20),
        ),
    ]
