# Generated by Django 3.1 on 2021-03-30 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210326_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aboutme',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contactno',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postalcode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='socialcontacts',
        ),
    ]
