# Generated by Django 3.1 on 2021-03-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aboutme',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contactno',
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='contactnumber',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Sri Lanka', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postalcode',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
