# Generated by Django 3.0.7 on 2021-06-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210330_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contactnumber',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='postalcode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='socialcontacts',
            new_name='social_contacts',
        ),
    ]
